kind: Deployment
apiVersion: apps/v1
metadata:
  name: testviz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testviz
  template:
    metadata:
      labels:
        app: testviz
    spec:
      serviceAccountName: pipeline-account
      containers:
      - name: testviz-demo
        image: public.ecr.aws/f9m0e7l8/publictest:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
      imagePullSecrets:
          - name: regcred
---

apiVersion: v1
kind: Service
metadata:
    name: testviz
spec:
    type: NodePort
    ports:
    - port: 3000
      targetPort: 3000
    selector:
        app: testviz