apiVersion: v1
kind: Pod
metadata:
  name: selenium-test-pod
  labels:
    app: selenium-test-pod
spec:
  serviceAccountName: pipeline-account
  containers:
    - name: mvn
      image: public.ecr.aws/f9m0e7l8/seletest:latest
      env:
        - name: WEBDRIVER_REMOTE_URL
          value: "http://10.102.8.21:4444/wd/hub"
        - name: CHROMEOPTIONS_ARGS
          value: "--headless"