kind: Deployment
apiVersion: apps/v1
metadata:
  name: selenium-test-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-test-pod
  template:
    metadata:
      labels:
        app: selenium-test-pod
    spec:
      serviceAccountName: pipeline-account
      containers:
      - name: mvn
        image: public.ecr.aws/f9m0e7l8/seletest:latest
        imagePullPolicy: Always
        env:
          - name: WEBDRIVER_REMOTE_URL
            value: "http://16.16.195.94:30737/wd/hub"
      imagePullSecrets:
          - name: regcred