export const permissionTypes = {
    GET_PERMISSION_LOADING: "GET_PERMISSION_LOADING",
    GET_PERMISSION_SUCCESS: "GET_PERMISSION_SUCCESS",
    GET_PERMISSION_FAILURE: "GET_PERMISSION_FAILURE",
    ADD_CAPABILITIES: "ADD_CAPABILITIES"
}