export const sprintTypes = {
    GET_SPRINTS_LOADING: "GET_SPRINTS_LOADING",
    GET_SPRINTS_SUCCESS: "GET_SPRINTS_SUCCESS",
    GET_SPRINTS_FAILURE: "GET_SPRINTS_FAILURE",
    ADD_SPRINT_ID: "ADD_SPRINT_ID",
    RESET_SPRINT_ID: "RESET_SPRINT_ID"
}